# Generated by Django 3.2.4 on 2021-06-22 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=30)),
                ('ClassDescription', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CodingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionName', models.CharField(default='', max_length=100)),
                ('Notes', models.CharField(max_length=500)),
                ('UploadDate', models.DateField(auto_now=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sequence', models.IntegerField()),
                ('Speech', models.CharField(max_length=500)),
                ('SessionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.codingsessions')),
            ],
        ),
        migrations.CreateModel(
            name='Codings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('KnownTrue', models.BooleanField()),
                ('TurnID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.turns')),
            ],
        ),
    ]
