# Generated by Django 3.2.4 on 2021-07-06 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClassName', models.CharField(max_length=30)),
                ('ClassShort', models.CharField(max_length=3, null=True)),
                ('ClassDescription', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CodingSessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SessionName', models.CharField(default='', max_length=100)),
                ('Notes', models.TextField(max_length=1000)),
                ('TranscriptLocation', models.CharField(max_length=255)),
                ('NextCoding', models.IntegerField()),
                ('NTurns', models.IntegerField()),
                ('UploadDate', models.DateField(auto_now_add=True)),
                ('UploadTime', models.TimeField(auto_now_add=True)),
                ('UserID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodingSchemaLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.codingschema')),
            ],
        ),
    ]
