# Generated by Django 3.2.4 on 2021-06-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turns',
            name='Speaker',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='codingsessions',
            name='UploadDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
