# Generated by Django 3.2.4 on 2021-06-25 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_codingsessions_userid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CodingClasses',
            new_name='CodingSchema',
        ),
    ]
