# Generated by Django 3.2.4 on 2021-06-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_codingclasses_codingschema'),
    ]

    operations = [
        migrations.AddField(
            model_name='codings',
            name='Coding',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.codingschema'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='CodingSchemaLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.IntegerField()),
                ('Coding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.codingschema')),
            ],
        ),
        migrations.AddField(
            model_name='codings',
            name='Level',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.codingschemalevels'),
            preserve_default=False,
        ),
    ]
