# Generated by Django 3.2.4 on 2021-06-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210625_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingschema',
            name='ClassShort',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='codingschemalevels',
            name='Coding',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='api.codingschema'),
        ),
    ]
