# Generated by Django 3.2.4 on 2021-06-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210625_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codingschema',
            name='ClassDescription',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='codingsessions',
            name='Notes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='turns',
            name='Speech',
            field=models.CharField(max_length=1000),
        ),
    ]
